baseurl: "/choir-guides"
title: "Variable Sheets"
permalink: pretty
exclude:
    - bin
    - composer.*
    - src
    - vendor

gems:
    - jemoji
    - jekyll-sitemap

timezone: America/New_York
defaults:
    -
        scope:
            path: ""
        values:
            author: "Jeremy Pry"
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "sheet"
            little_ektenia_3: 1
            normal_exaposteilarion: true
            great_doxology: null
            liturgy_right: true
            ascension: true
            overrides:
                kathismata: null
                evlogetaria: null
                doxastikon: null
            kontakion: false
            megalynarion: false
            koinonikon: false

kramdown:
    parse_block_html: true
    input: GFM
