baseurl: "/choir-guides"
title: "Variable Sheets"
permalink: pretty
exclude:
    - bin
    - composer.*
    - src
    - vendor

gems:
    - jemoji
    - jekyll-sitemap

collections:
    feasts:
        output: true

timezone: America/New_York
defaults:
    -
        scope:
            path: ""
        values:
            author: "Jeremy Pry"
            god_is_the_lord: null
            kathismata: null
            evlogetaria: null
            prokeimenon: null
            little_ektenia_3: 1
            normal_exaposteilarion: true
            doxastikon: null
            great_doxology: null
            troparion: null
            liturgy_right: true
            ascension: true
            kontakion: false
            megalynarion: false
            koinonikon: false
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "sheet"
    -
        scope:
            path: ""
            type: "feasts"
        values:
            layout: "feast"

kramdown:
    parse_block_html: true
    input: GFM
